name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.7
          gemfile: Gemfile
        - ruby: 2.7
          gemfile: gemfiles/rails60.gemfile
        - ruby: 2.6
          gemfile: gemfiles/rails52.gemfile
        - ruby: 2.5
          gemfile: gemfiles/rails51.gemfile
        - ruby: 2.4
          gemfile: gemfiles/rails50.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake test
